# Plugins
gems:             ["jekyll-paginate", "jekyll-gist", "jekyll-github-metadata"]

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "OpenLab project"
tagline:          "Mad people for Mad projects"
description:      "Tutorials su sviluppo web e tecnologie"
url:              https://mad-labs.github.io
baseurl:          /

author:
  name:           "Manfredi Gabriele"
  url:            ""

paginate:         5
paginate_path:    "/blog/page:num/"

# Custom vars
version:          0.1

github:
  repo:           https://github.com/Mad-Labs/Mad-Labs.github.io.git
