# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Madlabs - Open Lab poject
tagline:          Mad people for mad projects
description:      "Tutorial series on web coding"
url:              https://mad-labs.github.io
baseurl:          /

author:
  name:           'Manfredi Gabriele'
  url:            ''

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/Mad-Labs/Mad-Labs.github.io.git
