# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            MadLabs
tagline:          Mad projects from mad people
description:      "bla bla bla"
url:              https://mad-labs.github.io/
baseurl:          /

paginate:         5

# Custom vars
version:          0

github:
  repo:           https://mad-labs.github.io
